### PR TITLE
Modify version to work better with the update bot

### PR DESCRIPTION
**Pull request by chrisburr**
@conda-forge-admin, please rerender

### CODE REVIEW

**Comment by petrushy** [comment]
Hi! Many thanks for looking into this, but must there be a link between the artifact file and the version number? Sometimes I don't update the artifact file and have a new build number due to rerender for example? I would prefer to have these separated if ok?

**Comment by petrushy** [comment]
Maybe I should point out that this is a wrapper of a java library, so I want to keep the python matching to that version rather than have a separate system for the python fork.

**Comment by chrisburr** [comment]
Sorry I don't understand, the version on GitHub appears to be `10.0.4`? If not, how is the bot supposed to know what the version number is?

The build number is mostly designed to be incremented when the conda package changes to fix bugs in the packaging or when an update is made to the dependencies.

**Comment by petrushy** [comment]
Hi, I am creating the github file in order to build this conda package. The version is 10.0 based on the java version that the library is based on. I increaste the zip file numbe suffixr when needed for a recompile or some other bug fix. I would prefer to manage the version number for the conda package by hand and not have the bot changing it? Is it possible to mark the package for not having the bot to change the version number? 

Many thanks for supporting.

**Comment by petrushy** [comment]
Closing this as the number in the artifact is not hard linked to the build number.

**Pull request closed without merging**
